services:      
  backend-1:
    build:
      context: ./backend
    container_name: demo-ha-1
    networks:
      - demo_ha_network
  
  backend-2:
    build:
      context: ./backend
    container_name: demo-ha-2
    networks:
      - demo_ha_network
  
  nginx:
    image: nginx:latest
    container_name: nginx-ha
    depends_on:
      - backend-1
      - backend-2
    volumes:
      #- E:\Documents\Projects\DevOps\ha-dr\proxy\default.conf:/etc/nginx/conf.d/default.conf
      - E:\Documents\Projects\DevOps\ha-dr\proxy\nginx.conf:/etc/nginx/nginx.conf
      - E:\Documents\Projects\DevOps\ha-dr\proxy\log:/var/log/nginx
    ports:
      - "8080:80"
    networks:
      - demo_ha_network
  
networks:
  demo_ha_network:
    driver: bridge
    name: demo_ha_network